# Generated by Django 4.1.6 on 2023-02-17 15:29

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(default=book.models.default_genre, max_length=200),
        ),
    ]
