# Generated by Django 4.1.6 on 2023-02-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_book_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
