# Generated by Django 4.1.7 on 2023-03-28 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(default='', max_length=100)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, serialize=False, verbose_name='ID')),
                ('card_num', models.BigIntegerField()),
                ('card_name', models.CharField(max_length=200)),
                ('cvv', models.IntegerField()),
                ('ref_username', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Profile.profile')),
            ],
        ),
    ]
