# Generated by Django 4.1.6 on 2023-02-17 14:41

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copiesSold',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default={'author': 'Unknown Author'}, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(default=book.models.default_genre, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default={'title': 'Unknown Title'}, max_length=200),
        ),
    ]
