# Generated by Django 4.1.6 on 2023-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_author_alter_book_copiessold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
