# Generated by Django 4.1.6 on 2023-02-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
